var cities = ["Atlanta", "Baltimore", "Chicago", "Denver", "Los Angeles", "Seattle"];
alert("Welcome to " + cities[3]);
var mixedArray = [1, "Bob", "Now is", true];
var names =[];
// var name = prompt("suggest a name");
names[0] = "Tooba";
names[1] = "Abullah";
names[2] = "Hassan";
var pets = [];
pets[0] = "dog";
pets[1] = "cat";
pets[2] = "bird";
pets[3] = "lizard";
pets[6] = "snake";
pets[3] = "lizard";
pets[4] = "fish";
pets[5] = "gerbil";
pets[6] = "snake";
console.log(pets);
alert(pets);
alert(names);
pets.pop();
console.log(pets);
pets.push("fish","cow");
console.log(pets);